name: Update gist with WakaTime stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7c688d0a3cdbedea5615124f76c82c67
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
